root = "."

[build]
args_bin = []
bin = "main.exe"
cmd = "go build -buildvcs=false -o main.exe ."

delay = 1000

exclude_dir = ["app", "ssl"]

follow_symlink = false
full_bin = ""

include_ext = ["go", "tpl", "tmpl", "html"]

kill_delay = "0s"
log = "air-errors.log"

send_interrupt = true
stop_on_error = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
